CREATE TABLE USER (
    UUID VARCHAR(255) NOT NULL,
    NAME VARCHAR2(30),
    EMAIL VARCHAR2(30),
	PASSWORD VARCHAR2(20),
	CREATED TIMESTAMP(0),
	MODIFIED TIMESTAMP(0),
	LAST_LOGIN TIMESTAMP(0),
	TOKEN VARCHAR2(20),
	ISACTIVE VARCHAR2(20)
);

CREATE TABLE PHONE (
    UUID VARCHAR(255) NOT NULL,
    USER STRING AS UUID,
    NUMBER VARCHAR2(30),
	CITYDOCE VARCHAR2(20),
	CONTRYCODE TIMESTAMP(0)
);